<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DonorWebController;
use App\Http\Controllers\DonationWebController;
use App\Http\Controllers\WarehouseWebController;
use App\Http\Controllers\ItemWebController;
use App\Http\Controllers\InventoryTransactionWebController;
use App\Http\Controllers\BeneficiaryWebController;
use App\Http\Controllers\ExpenseWebController;
use App\Http\Controllers\FinancialClosureWebController;
use App\Http\Controllers\AttachmentWebController;
use App\Http\Controllers\DelegateWebController;
use App\Http\Controllers\TravelRouteWebController;
use App\Http\Controllers\ReportsWebController;
use App\Http\Controllers\UserWebController;
use App\Http\Controllers\RoleWebController;
use App\Http\Controllers\ComplaintWebController;
use App\Http\Controllers\VolunteerHourWebController;
use App\Http\Controllers\PayrollWebController;
use App\Http\Controllers\LoginWebController;
use App\Http\Controllers\VolunteerAttendanceWebController;
use App\Http\Controllers\TaskWebController;
use App\Http\Controllers\VolunteerWebController;
use App\Http\Controllers\DashboardWebController;
use App\Http\Controllers\AuditWebController;
use App\Http\Controllers\NotificationWebController;
use App\Http\Controllers\ProjectWebController;
use App\Http\Controllers\CampaignWebController;
use App\Http\Controllers\GuestHouseWebController;

Route::get('/', function(){ return redirect()->route('dashboard.index'); });
Route::get('login', [LoginWebController::class, 'show'])->name('login');
Route::post('login', [LoginWebController::class, 'login'])->name('login.post');
Route::post('logout', [LoginWebController::class, 'logout'])->name('logout');

Route::middleware([\App\Http\Middleware\WebAuth::class])->group(function () {
Route::get('dashboard', [DashboardWebController::class,'index'])->name('dashboard.index');
Route::get('notifications', [NotificationWebController::class,'index'])->name('notifications.index');
Route::get('audits', [AuditWebController::class,'index'])->name('audits.index');
Route::resource('donors', DonorWebController::class);
Route::resource('donations', DonationWebController::class);
Route::resource('warehouses', WarehouseWebController::class);
Route::resource('items', ItemWebController::class);
Route::resource('inventory-transactions', InventoryTransactionWebController::class);
Route::resource('beneficiaries', BeneficiaryWebController::class);
Route::resource('expenses', ExpenseWebController::class);
Route::get('finance/closures', [FinancialClosureWebController::class,'index'])->name('closures.index');
Route::get('finance/closures/create', [FinancialClosureWebController::class,'create'])->name('closures.create');
Route::post('finance/closures', [FinancialClosureWebController::class,'store'])->name('closures.store');
Route::post('finance/closures/{closure}/approve', [FinancialClosureWebController::class,'approve'])->name('closures.approve');
Route::post('attachments', [AttachmentWebController::class,'store'])->name('attachments.store');
Route::delete('attachments/{attachment}', [AttachmentWebController::class,'destroy'])->name('attachments.destroy');
Route::resource('delegates', DelegateWebController::class);
Route::resource('travel-routes', TravelRouteWebController::class);
Route::get('reports', [ReportsWebController::class,'index'])->name('reports.index');
Route::resource('users', UserWebController::class);
Route::resource('roles', RoleWebController::class);
Route::post('users/{user}/roles/{role}', [UserWebController::class,'attachRole'])->name('users.attachRole');
Route::delete('users/{user}/roles/{role}', [UserWebController::class,'detachRole'])->name('users.detachRole');
Route::resource('complaints', ComplaintWebController::class);
Route::resource('volunteer-hours', VolunteerHourWebController::class);
Route::resource('payrolls', PayrollWebController::class);
Route::resource('volunteer-attendance', VolunteerAttendanceWebController::class);
Route::resource('tasks', TaskWebController::class);
Route::resource('volunteers', VolunteerWebController::class);
Route::get('volunteers/reports', [VolunteerWebController::class,'reports'])->name('volunteers.reports');
Route::resource('projects', ProjectWebController::class);
Route::post('projects/{project}/manager', [ProjectWebController::class,'setManager'])->name('projects.setManager');
Route::post('projects/{project}/deputy', [ProjectWebController::class,'setDeputy'])->name('projects.setDeputy');
Route::post('projects/{project}/volunteers', [ProjectWebController::class,'attachVolunteer'])->name('projects.attachVolunteer');
Route::delete('projects/{project}/volunteers/{user}', [ProjectWebController::class,'detachVolunteer'])->name('projects.detachVolunteer');
Route::resource('campaigns', CampaignWebController::class);
Route::resource('guest-houses', GuestHouseWebController::class);
Route::view('hr/evaluations', 'hr.evaluations')->name('hr.evaluations');
});
